apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wbolz5cnr-go 
  janus-idp.io/tekton: wbolz5cnr-go
  backstage.io/kubernetes-id: wbolz5cnr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbolz5cnr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml