apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wbolz5cnr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wbolz5cnr-go 
  name: wbolz5cnr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wbolz5cnr-go 
